### ISSUE TITLE
在这里请教一下防止微信强制升级的方法

### ISSUE THREAD

**Issue by amibk** [cixingguangming55555/wechat-bot#104]
我安装完之前的版本，只要电脑一重启，再次打开微信客户端就会被强制升级。然后只能卸载重装之前的版本。
注意我这里在安装完之前版本后立即就去掉了【有更新时自动升级微信】这个选项，但是还是在下次打开时被强制更新
这样反反复复的卸载再安装太麻烦了，请教各位是怎么防止被强制更新的？

**Comment by cixingguangming55555** [comment]
去群里问吧，有人有解决办法。
