### ISSUE TITLE
求助关于获取不到完整图片的问题

### ISSUE THREAD

**Issue by endison1986** [cixingguangming55555/wechat-bot#130]
与服务端的通讯已经可以了，并且可以拦截到文本和图片。
问题一
解析图片数据时发现保存了缩略图和完整的图片两个路径。但是在磁盘上只能找到缩略图，找不到完整图片，微信似乎需要点击缩略图后才会下载大图
问题二
同样解析图片数据时发现保存了缩略图和疑似完整图片的加密后路径，从数据格式看是hex的，转成字符串后部分是乱码，根据aeskey的名字，推断使用了aes的加密方式，但仍然无法解析url的明文。

所以现在来请求帮助
1.是否可以帮忙下载完整图片或者提供接口下载完整图片
2.是否可以帮忙看看怎么解析这串url，感觉aeskey是用来解析url下载后的数据，url是不是有别的方式转成明文

**Comment by dreamage** [comment]
百度微信图片dat  有算法

**Comment by endison1986** [comment]
> 百度微信图片dat 有算法

dat算法早就搞定了，但是本地磁盘里只有缩略图，大图需要点击缩略图才会下载
