### ISSUE TITLE
发送图片可以直接用http链接吗？

### ISSUE THREAD

**Issue by JoffreyN** [cixingguangming55555/wechat-bot#138]
我试了不行，可以增加这个功能吗嘛？

**Comment by cixingguangming55555** [comment]
可以啊

**Comment by tuvy** [comment]
我的也是，用把本地图片路径替换为url图片，发送后，控制台能显示，都是微信里接收不到

**Comment by cixingguangming55555** [comment]
发送图片的逻辑是：微信会从本地的路径下去拿图片文件，发送出去。你要通过http发，不是直接发，而是先把http的图片下载到你指定目录，然后调用dll的sendpic
