### ISSUE TITLE
ERROR: 'function' object has no attribute 'SSLSocket'

### ISSUE THREAD

**Issue by n1000g** [cixingguangming55555/wechat-bot#159]
报错信息
--- request header ---
GET / HTTP/1.1
Upgrade: websocket
Host: localhost:5555
Origin: http://localhost:5555
Sec-WebSocket-Key: bVeWN+d9Fs8iRKEmo5/nsQ==
Sec-WebSocket-Version: 13
Connection: Upgrade

-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Sec-WebSocket-Accept: YSt33vjkh7fT30WjTxVDeawbHE0=
Server: WebSocket++/0.8.2
Upgrade: websocket
-----------------------
error! ws =  <websocket._app.WebSocketApp object at 0x000000A978E5AAF0>
'function' object has no attribute 'SSLSocket'
send: b'\x88\x82\xfa\xb2\xd4\n\xf9Z'
### start closed ###
ws =  <websocket._app.WebSocketApp object at 0x000000A978E5AAF0>
close_status_code =  None
close_msg =  None

**Comment by cixingguangming55555** [comment]
看cliet下面具体的语言示例。或把代码贴出来

**Comment by n1000g** [comment]
> 看cliet下面具体的语言示例。或把代码贴出来

这个错误应该跟项目无关，是环境问题，跑的每个 python demo 都报同这个一样的错误，前几天重启服务器后，重试了下正常了
