### ISSUE TITLE
6500 获取用户信息返回体异常

### ISSUE THREAD

**Issue by rainsunset** [cixingguangming55555/wechat-bot#167]
版本：3.2.1.121-0.0.0.015_稳定版.dll
url: /api/get_personal_info
请求体：{"id":"1661857583659","wxid":"ROOT","type":6500,"content":"op:personal info","roomid":"null","nickname":"null","ext":"null"}
返回体： {"content":"{\"wx_code\":\"PPq\\u0006\",\"wx_id\":\"PPq\\u0006\",\"wx_name\":\"池\"}","id":"1661857583659","receiver":"CLIENT","sender":"SERVER","srvid":1,"status":"SUCCSESSED","time":"2022-08-30 19:06:23","type":6500}

其中：  PPq\\u0006  不是正确的wx_id

**Comment by cixingguangming55555** [comment]
近期会处理这个bug

**Comment by cixingguangming55555** [comment]
QQ群有个测试代码，你测测看
