### ISSUE TITLE
发送消息错误

### ISSUE THREAD

**Issue by hhhhhhhhai** [cixingguangming55555/wechat-bot#168]
群消息/私聊
[json.exception.type_error.302] type must be string, but is null

微信版本/注入dll 3.6.0.18

**Comment by cixingguangming55555** [comment]
参数构造有问题，
/**send_pic
 *  发送图片
 */
async function send_pic()
{
  const jpara={
    id:getid(),
    type:PIC_MSG,
    wxid:'your id(wxid or roomid)',//23023281066@chatroom
    roomid:'null',
    content:'C:\\tmp\\2.jpg',
    nickname:"null",
    ext:'null'
    //wxid:'22428457414@chatroom'
    
  };
  
    const options =
      {
          //method: 'GET',
          //url: 'https://apis.map.qq.com/ws/district/v1/list',
          url: url+'/api/sendpic',
          body:{
            para:jpara
        },
        json:true
      };
      let data = await rp(options);
      //const j = JSON.parse(data);
      
      //console.log(j.id); 
      //console.log(j.status);
      return data;


}
