### ISSUE TITLE
get_personal_detail 无法通过wx_id获取好友信息

### ISSUE THREAD

**Issue by SnapdragonLee** [cixingguangming55555/wechat-bot#188]
Version: 3.6.0.18

Program(Python):
```
def get_personal_detail(wx_id):
    qs = {
        'id': getid(),
        'type': PERSONAL_DETAIL,
        'wxid': wx_id,
        'roomid': 'null',
        'content': 'null',
        'nickname': "null",
        'ext': 'null'
    }
    s = json.dumps(qs)
    return s
```

Output：
{'content': {'big_headimg': '⏠ຐz', 'cover': '컨ᄧk', 'little_headimg': '⏠ຐz', 'signature': '脀Ⴗ\x02'}, 'id': '20230219001112', 'receiver': 'CLIENT', 'sender': 'SERVER', 'srvid': 1, 'status': 'SUCCSESSED', 'time': '2023-02-19 00:11:12', 'type': 6550}

还有找不到QQ群，希望给个新群号，谢谢

**Comment by cixingguangming55555** [comment]
等我电脑修好了，看看你这个问题

**Comment by SnapdragonLee** [comment]
好的谢谢您，希望可以尽快，谢谢！
