### ISSUE TITLE
获取真实MsgID

### ISSUE THREAD

**Issue by yi-ge** [cixingguangming55555/wechat-bot#205]
根据socket推送过来的信息判断，id是时间戳，而获取原图需要用到真实的MsgId，希望能增加真实消息ID的推送。

**Comment by cixingguangming55555** [comment]
不知道wechat有没有你说的这个msgid，这个真实ID有什么作用？

**Comment by yi-ge** [comment]
实测[3.9.2.23]版本白天也出现不自动下载原图的情况，下载原图有两种方法，一种是MsgId+skey，另一种是CDN通过file_id, file_type, aes_key下载。希望通过MsgId使用第一种方法进行下载。

**Comment by atorber** [comment]
> 实测[3.9.2.23]版本白天也出现不自动下载原图的情况，下载原图有两种方法，一种是MsgId+skey，另一种是CDN通过file_id, file_type, aes_key下载。希望通过MsgId使用第一种方法进行下载。

具体的方法可以分享一下吗
