### ISSUE TITLE
微信发送消息失败

### ISSUE THREAD

**Issue by dindenyu** [cixingguangming55555/wechat-bot#21]
在微信运行期间，收到了好友申请，手动点了同意好友申请。
然后这个好友发消息来，接收是没有问题的。
get_personal_detail，获取好友个人信息的时候，返回的数据是成功没问题的。
但是在给他发送消息的时候，会发送失败，"status":"FAIL"，"content":"send text msg:wxid ，its not on your friend list！"。
获取微信通讯录好友wxid和名字，返回的清单里没有这个好友。
请确认是否是bug，谢谢。

**Comment by cixingguangming55555** [comment]
我确认一下，估计是个BUG！

**Comment by cixingguangming55555** [comment]
是个BUG，我尽快处理！

**Comment by cixingguangming55555** [comment]
临时处理办法是：重启微信和重新注入。

**Comment by cixingguangming55555** [comment]
buf was fixed!

**Comment by cixingguangming55555** [comment]
not yet

**Comment by xjq1019** [comment]
这个有修复计划吗？
