### ISSUE TITLE
使用接口提供的获取联系人和群组的方法，无返回结果

### ISSUE THREAD

**Issue by voodooq** [cixingguangming55555/wechat-bot#26]
格式参考：
https://www.showdoc.cc/wechatbot?page_id=3962180315692880

收到消息：{"content":"the data not ready!","id":"1586848345823","sender":"ROOT","srvid":1,"status":"FAIL","time":"2020-3-14 15:12:25","type":5010,"wxid":"ROOT"}

**Comment by voodooq** [comment]
已经解决

**Comment by sczhoubing** [comment]
> 已经解决

我也有同样的问题，你是怎么解决的呢

**Comment by khmfighter** [comment]
> > 已经解决
> 
> 我也有同样的问题，你是怎么解决的呢

我也是同样的问题，不知道怎么解决~
