### ISSUE TITLE
获取某个群的昵称列表时微信主程序崩溃

### ISSUE THREAD

**Issue by achillis2016** [cixingguangming55555/wechat-bot#32]
此Bug可稳定重现，疑似空指针导致内存访问错误

(21d4.22a0): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=00000000 ebx=15a5f924 ecx=00000000 edx=00000000 esi=0a559de0 edi=00000002
eip=1474f602 esp=15a5f000 ebp=15a5f848 iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
*** WARNING: Unable to verify checksum for F:\Programs2018\WeChat\wechat-bot-master\server\version2.8.0.121-2.5.3.58.dll
*** ERROR: Module load completed but symbols could not be loaded for F:\Programs2018\WeChat\wechat-bot-master\server\version2.8.0.121-2.5.3.58.dll
version2_8_0_121_2_5_3_58+0x2f602:
1474f602 668b01          mov     ax,word ptr [ecx]        ds:002b:00000000=????
0:048> kvn
 # ChildEBP RetAddr  Args to Child              
WARNING: Stack unwind information not available. Following frames may be wrong.
00 15a5f848 1474e2b4 0a55b800 5376b423 12a4f2a8 version2_8_0_121_2_5_3_58+0x2f602
01 15a5f970 14733155 15a5fa34 5376b7df 15a5fb50 version2_8_0_121_2_5_3_58+0x2e2b4
02 15a5fa8c 14733f4e 5376b79f 14733eb0 12a4f2a8 version2_8_0_121_2_5_3_58+0x13155
03 15a5facc 1474b20d 12a4f2a8 00000071 15a5fb50 version2_8_0_121_2_5_3_58+0x13f4e
04 15a5faf8 1474b670 00000003 12a4f2a8 15a5fba8 version2_8_0_121_2_5_3_58+0x2b20d
05 15a5fb68 1474b917 1474b8e0 12a4f2a8 00000100 version2_8_0_121_2_5_3_58+0x2b670
06 15a5fb84 147421be 12a4f2a8 00000003 15a5fba8 version2_8_0_121_2_5_3_58+0x2b917
07 15a5fbb4 14742078 000005b4 00000001 12a4f2a8 version2_8_0_121_2_5_3_58+0x221be
08 15a5fbf0 147441cc 00000000 00000000 00000000 version2_8_0_121_2_5_3_58+0x22078
09 15a5ff4c 147342f6 05c162e8 000000c8 5376b2db version2_8_0_121_2_5_3_58+0x241cc
0a 15a5ff88 7dd7344d 00000000 15a5ffd4 7dea9802 version2_8_0_121_2_5_3_58+0x142f6
0b 15a5ff94 7dea9802 00000000 681c1d39 00000000 kernel32!BaseThreadInitThunk+0xe (FPO: [Non-Fpo])
0c 15a5ffd4 7dea97d5 14734210 00000000 00000000 ntdll!__RtlUserThreadStart+0x70 (FPO: [Non-Fpo])
0d 15a5ffec 00000000 14734210 00000000 00000000 ntdll!_RtlUserThreadStart+0x1b (FPO: [Non-Fpo])

**Comment by cixingguangming55555** [comment]
非指针问题
