### ISSUE TITLE
op:personal info is no return

### ISSUE THREAD

**Issue by cixingguangming55555** [cixingguangming55555/wechat-bot#38]

**Comment by cixingguangming55555** [comment]
There are still problems

**Comment by caojiurui** [comment]
client.js 发送内容为： {
				id: getid(),
				type: PERSONAL_INFO,
				content: 'op:personal info',
				wxid: 'null'
			}

响应结果为：
{
	"content": "json:dump error!",
	"id": "1601739686954",
	"sender": "ROOT",
	"srvid": 1,
	"status": "FAIL",
	"time": "2020-10-03 23:41:26",
	"type": 6500,
	"wxid": "ROOT"
}

**Comment by cixingguangming55555** [comment]
C:\vc\github\version>node client.js
{
  content: {
    city: 'Kunming',
    country: 'CN',
    headimg132: 'http://wx.qlogo.cn/mmhead/ver_1/IaoA2YAyDuZXNU8ElFg5byuZ4b4IRibcicBfiao5jKjicCq645mu7CVLA1iayrhnTs9v0rzOI1aqsYjBA7PSSRAibbg1evNo9ZCicmqnnCuiayxPSic8/132',
    headimg959: 'http://wx.qlogo.cn/mmhead/ver_1/OianIwTR6CCibzt3BicOXmJ8cGUP0ou5cN5K923jJNNhCWmj30MV4PUjUY2C33rE2TegXgBydyJCohoia8FAgiaJh3zD9PnEdpV7nyUibDb2tqLh0/0',
    mail: '18656197@qq.com',
    mobile: '13551376550',
    nick: '老张学技术',
    province: 'Yunnan',
    wx_code: 'hongzhaoyuanma',
    wxid: 'wxid_lbca2qnlir9h22'
  },
  id: '1607253890662',
  sender: 'ROOT',
  srvid: 1,
  status: 'SUCCESS',
  time: '2020-12-06 19:24:50',
  type: 6500,
  wxid: 'ROOT'
}
{
  content: {
    city: 'Kunming',
    country: 'CN',
    headimg132: 'http://wx.qlogo.cn/mmhead/ver_1/IaoA2YAyDuZXNU8ElFg5byuZ4b4IRibcicBfiao5jKjicCq645mu7CVLA1iayrhnTs9v0rzOI1aqsYjBA7PSSRAibbg1evNo9ZCicmqnnCuiayxPSic8/132',
    headimg959: 'http://wx.qlogo.cn/mmhead/ver_1/OianIwTR6CCibzt3BicOXmJ8cGUP0ou5cN5K923jJNNhCWmj30MV4PUjUY2C33rE2TegXgBydyJCohoia8FAgiaJh3zD9PnEdpV7nyUibDb2tqLh0/0',
    mail: '18656197@qq.com',
    mobile: '13551376550',
    nick: '老张学技术',
    province: 'Yunnan',
    wx_code: 'hongzhaoyuanma',
    wxid: 'wxid_lbca2qnlir9h22'
  },
  id: '1607253890662',
  sender: 'ROOT',
  srvid: 1,
  status: 'SUCCESS',
  time: '2020-12-06 19:24:50',
  type: 6500,
  wxid: 'ROOT'
}

这个是get_personal_info

**Comment by cixingguangming55555** [comment]
/**  通过wxid获取好友详细细腻
   * ws.send(get_personal_detail());
   */
