### ISSUE TITLE
仓库内提供的2.8.0.121版本提取码错误

### ISSUE THREAD

**Issue by Zoranner** [cixingguangming55555/wechat-bot#52]
希望可以更新一下提取码，因为这个版本真的蛮难找的🤐

**Comment by cixingguangming55555** [comment]
https://pan.baidu.com/s/1jrW2HzBxM8wceZRn8hT5UQ
提取码：ye2w

**Comment by Zoranner** [comment]
> https://pan.baidu.com/s/1jrW2HzBxM8wceZRn8hT5UQ
> 提取码：ye2w

谢谢🙇‍♂️
