### ISSUE TITLE
无法发送gif图片，会自动转为静态图

### ISSUE THREAD

**Issue by caojiurui** [cixingguangming55555/wechat-bot#62]
![image](https://user-images.githubusercontent.com/16349022/86525314-2a3b2300-beb8-11ea-9d3a-afc97acf1edd.png)
![image](https://user-images.githubusercontent.com/16349022/86525318-43dc6a80-beb8-11ea-8346-2ecc8cecb746.png)

**Comment by cixingguangming55555** [comment]
是的，没这个功能。暂时也不考虑实现。
