### ISSUE TITLE
ws.send后无响应

### ISSUE THREAD

**Issue by ly1ex** [cixingguangming55555/wechat-bot#73]
ws.send后无相应
![image](https://user-images.githubusercontent.com/25427168/96010215-27b37680-0e74-11eb-832d-182df3365d6c.png)
print的第一行是发送的请求
但是没有相应。
只有接收消息是正常的
微信2.8，2.9版本均测试有此问题
请问可能是什么原因？

**Comment by lyleshaw** [comment]
使用HTTP协议正常
