### ISSUE TITLE
get_personal_detail 接口，返回消息错误

### ISSUE THREAD

**Issue by caojiurui** [cixingguangming55555/wechat-bot#74]
发送获取个人详情接口
随便输入一个wxid_000
ws.send(get_personal_detail('wxid_000'));
![image](https://user-images.githubusercontent.com/16349022/96357586-7856f800-1130-11eb-9a48-6c8bf9eb8f3b.png)

仍然可以响应数据
![image](https://user-images.githubusercontent.com/16349022/96357597-93c20300-1130-11eb-94ac-5aa4231d31b0.png)

**Comment by cixingguangming55555** [comment]
fixed it
