### ISSUE TITLE
Python 带交互界面客户端申请出战（界面基于PyQT）

### ISSUE THREAD

**Issue by lzx8589561** [cixingguangming55555/wechat-bot#75]
![image](https://user-images.githubusercontent.com/24806146/97077236-93d07000-1614-11eb-85bf-948f9d773a65.png)
![image](https://user-images.githubusercontent.com/24806146/97077243-9e8b0500-1614-11eb-8420-f5adce3564cd.png)
![image](https://user-images.githubusercontent.com/24806146/97077245-a480e600-1614-11eb-840b-a412009f0fc0.png)

开源地址
https://github.com/lzx8589561/ZTool

**Comment by hongzhaoyuanma** [comment]
厉害，加油！
