### ISSUE TITLE
HTTP发送图片失败

### ISSUE THREAD

**Issue by 286844626** [cixingguangming55555/wechat-bot#79]
data={"id":getid,"type":"500","wxid":"filehelper","content":r"\image\0000.jpg"}
a=requests.post("http://127.0.0.1:5555/api/sendpic",data=data)
print(a.text)

return:{"content":"send pic msg:wxid is not on your friend list!","id":"","sender":"ROOT","srvid":1,"status":"FAILED","time":"","type":500,"wxid":"ROOT"}

**Comment by cixingguangming55555** [comment]
C:\vc\github\version>node client.js
{"id":"1607253344377","type":500,"content":"C:\\Users\\14988\\Desktop\\temp\\2.jpg","wxid":"filehelper"}
{
  content: 'send pic msg:the pic sended succsecc!',
  id: '1607253344377',
  sender: 'ROOT',
  srvid: 1,
  status: 'SUCCESS',
  time: '2020-12-06 19:15:44',
  type: 500,
  wxid: 'ROOT'
}
{
  content: 'send pic msg:the pic sended succsecc!',
  id: '1607253344377',
  sender: 'ROOT',
  srvid: 1,
  status: 'SUCCESS',
  time: '2020-12-06 19:15:44',
  type: 500,
  wxid: 'ROOT'
}

我测试过，没有问题
