### ISSUE TITLE
消息重复

### ISSUE THREAD

**Issue by vipxiaoma** [cixingguangming55555/wechat-bot#80]
发送不同消息，接收到相同消息

如同时发送：
     A、B两条消息，微信客户端收到两条相同的B消息，消息A被覆盖了

使用消息队列发送问题依旧存在

使用协议是webSocket

**Comment by choosecoin** [comment]
没有使用一样的id吧

**Comment by vipxiaoma** [comment]
> 两条消息使用相同的id，会有这种情况

不同id也会这样，webSocket
