### ISSUE TITLE
get_personal_detail接口问题

### ISSUE THREAD

**Issue by choosecoin** [cixingguangming55555/wechat-bot#83]
调试发现 get_personal_detail 接口返回的不是我请求的wxid信息
第一个wxid获取的没问题，换一个就有问题了

**Comment by cixingguangming55555** [comment]
{
  content: {
    big_headimg: '',
    city: '',
    cover: '',
    little_headimg: '',
    name1: '',
    name2: 'Z',
    nation: '',
    provice: '',
    signature: '',
    v1: '@stranger',
    wxcode: ''
  },
  id: '1607514546552',
  sender: 'ROOT',
  srvid: 1,
  status: 'SUCCESS',
  time: '2020-12-09 19:49:06',
  type: 6550,
  wxid: 'ROOT'
}
{
  content: {
    big_headimg: '',
    city: '',
    cover: '',
    little_headimg: '',
    name1: '',
    name2: 'Z',
    nation: '',
    provice: '',
    signature: '',
    v1: '@stranger',
    wxcode: ''
  },
  id: '1607514546552',
  sender: 'ROOT',
  srvid: 1,
  status: 'SUCCESS',
  time: '2020-12-09 19:49:06',
  type: 6550,
  wxid: 'ROOT'
}

**Comment by cixingguangming55555** [comment]
没问题哈
