### ISSUE TITLE
获取用户信息返回错误信息

### ISSUE THREAD

**Issue by machaochun** [cixingguangming55555/wechat-bot#90]
请求参数
 "id":"20201218184516","type":6500,"content":"op:personal info","wxid":"ROOT"}
返回参数
{"content":"json:dump error!","id":"20201218184516","sender":"ROOT","srvid":1,"status":"FAIL","time":"2020-12-18 18:45:16","type":6500,"wxid":"ROOT"}

**Comment by cixingguangming55555** [comment]
看看新版本，3.1.0.66呢，还有错没？

**Comment by cixingguangming55555** [comment]
请使用3.1.0.66版本
