### ISSUE TITLE
微信客户端提示版本过低,无法登录

### ISSUE THREAD

**Issue by teg1c** [cixingguangming55555/wechat-bot#91]
大家有遇到嘛

**Comment by hongzhaoyuanma** [comment]
2.9.0.123这个微信版本

**Comment by teg1c** [comment]
> 2.9.0.123这个微信版本

两个版本都提示这个

**Comment by hongzhaoyuanma** [comment]
version2.9.0.123-4.5.7.73.dll，这个表示微信的版本是2.9.0.123，用对了版本是没有问题的。

**Comment by teg1c** [comment]
> version2.9.0.123-4.5.7.73.dll，这个表示微信的版本是2.9.0.123，用对了版本是没有问题的。

server 我都还没注入,登录微信就提示这个

**Comment by teg1c** [comment]
卸载后安装最新版,登录,然后卸载安装2.9就可以了
