### ISSUE TITLE
2.9.0.123 已经无法登录

### ISSUE THREAD

**Issue by gtf35** [cixingguangming55555/wechat-bot#92]
2.9.0.123 这个版本登录的时候已经提示版本过低无法登录，用新版本登录之后再覆盖回旧版本也不可
![image](https://user-images.githubusercontent.com/22125696/104083097-ae5ed080-5276-11eb-9009-919d4f39b670.png)

**Comment by gtf35** [comment]
![ban](https://user-images.githubusercontent.com/22125696/104141081-cf96fc80-53ef-11eb-9d74-074c8ca2f772.jpg)
小号那天登陆不了之后就没再动过，然后发现 www

**Comment by hongzhaoyuanma** [comment]
等3.1.0.66

**Comment by zyzbeier** [comment]
是的，我也没法登录了，新切换老也不行，要等作者大大尽早更新了。。。急急急！！！

**Comment by zyzbeier** [comment]
> 等3.1.0.66

大概什么什么能出来，大佬

**Comment by cixingguangming55555** [comment]
已经有了啊

**Comment by 64161848** [comment]
3.1.0.66 客户端链接谁能给个 现在下都是3.1.0.72了
